# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Send Notification on master

on:
  push:
    branches:
      - "cd"
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  build:
    #if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Auth
        run: cd auth/ && ./build.sh && cd ../

      - name: Upload Auth
        uses: actions/upload-artifact@v3
        with:
          name: auth-app-build
          path: auth/build/AuthApp-001-build

      - name: Build Chat
        run: cd chat-app/ && ./build.sh && cd ../

      - name: Upload Chat
        uses: actions/upload-artifact@v3
        with:
          name: chat-app-build
          path: chat-app/build/ChatApp-001-build

      - name: Build Media Handler
        run: cd media-handler/ && ./build.sh && cd ../

      - name: Upload Media Handler
        uses: actions/upload-artifact@v3
        with:
          name: media-handler-build
          path: media-handler/build/MediaHandler-001-build

      - name: Build User Management
        run: cd user-mgmt/ && ./build.sh && cd ../

      - name: Upload User Management
        uses: actions/upload-artifact@v3
        with:
          name: user-mgmt-build
          path: user-mgmt/build/UserMgmt-001-build

      - name: Build Notification
        run: cd notification/ && ./build.sh && cd ../

      - name: Upload Notification
        uses: actions/upload-artifact@v3
        with:
          name: notification-build
          path: notification/build/NotificationApp-001-build

  telegram-notification:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send the build to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RELEASES_CHANNEL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ГООООООООООООООООООЛ!!!
          photo: test/goal.png
