# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Telegram_Notify

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send the build to telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_RELEASES_CHANNEL }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Гооооооооол!
        photo: './goal.png'
        document: goal.png
